version: '2'
services:
  jenkins:
    image: sadofrazer/jenkins
    restart: always
    ports:
      - '8080:8080'
      - '5000:5000'
    privileged: true
    volumes:
      - 'jenkins_home:/var/lib/jenkins/'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
volumes:
  jenkins_home:
    driver: local
